try {
  let a;
  console.log(a.length);
  console.log("Hi There");
} catch (e) {
  console.log("Inside Catch Block");
}

console.log("Hi There")
